apiVersion: v1
kind: Service
metadata:
  name: agentic-chatbot
spec:
  type: {{ .Values.service.type }}
  selector:
    app: agentic-chatbot
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000